# permissions for end users to edit demopods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demopod-editor-role
rules:
- apiGroups:
  - example.nati.com
  resources:
  - demopods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.nati.com
  resources:
  - demopods/status
  verbs:
  - get
