# permissions for end users to view demopods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demopod-viewer-role
rules:
- apiGroups:
  - example.nati.com
  resources:
  - demopods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.nati.com
  resources:
  - demopods/status
  verbs:
  - get
